doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Users:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Users/Domain/Model'
                prefix: 'App\Users\Domain\Model'
                alias: Users
            Cliente:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Cliente/Domain/Model'
                prefix: 'App\Cliente\Domain\Model'
                alias: Cliente
            Contrato:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Contrato/Domain/Model'
                prefix: 'App\Contrato\Domain\Model'
                alias: Contrato
            Direccion:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Direccion/Domain/Model'
                prefix: 'App\Direccion\Domain\Model'
                alias: Direccion
            Gasto:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Gasto/Domain/Model'
                prefix: 'App\Gasto\Domain\Model'
                alias: Gasto
            Ingreso:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ingreso/Domain/Model'
                prefix: 'App\Ingreso\Domain\Model'
                alias: Ingreso
            Local:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Local/Domain/Model'
                prefix: 'App\Local\Domain\Model'
                alias: Local
            Prestamo:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Prestamo/Domain/Model'
                prefix: 'App\Prestamo\Domain\Model'
                alias: Prestamo
            Trastero:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Trastero/Domain/Model'
                prefix: 'App\Trastero\Domain\Model'
                alias: Trastero
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
