# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Users module - Repository binding
    App\Users\Domain\Repository\UserRepositoryInterface:
        class: App\Users\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository

    # Direccion module - Repository binding
    App\Direccion\Domain\Repository\DireccionRepositoryInterface:
        class: App\Direccion\Infrastructure\Persistence\Doctrine\Repository\DoctrineDireccionRepository

    # Local module - Repository binding
    App\Local\Domain\Repository\LocalRepositoryInterface:
        class: App\Local\Infrastructure\Persistence\Doctrine\Repository\DoctrineLocalRepository

    # Gasto module - Repository binding
    App\Gasto\Domain\Repository\GastoRepositoryInterface:
        class: App\Gasto\Infrastructure\Persistence\Doctrine\Repository\DoctrineGastoRepository

    # Trastero module - Repository binding
    App\Trastero\Domain\Repository\TrasteroRepositoryInterface:
        class: App\Trastero\Infrastructure\Persistence\Doctrine\Repository\DoctrineTrasteroRepository

    # Cliente module - Repository binding
    App\Cliente\Domain\Repository\ClienteRepositoryInterface:
        class: App\Cliente\Infrastructure\Persistence\Doctrine\Repository\DoctrineClienteRepository

    # Contrato module - Repository binding
    App\Contrato\Domain\Repository\ContratoRepositoryInterface:
        class: App\Contrato\Infrastructure\Persistence\Doctrine\Repository\DoctrineContratoRepository

    # Ingreso module - Repository binding
    App\Ingreso\Domain\Repository\IngresoRepositoryInterface:
        class: App\Ingreso\Infrastructure\Persistence\Doctrine\Repository\DoctrineIngresoRepository

    # Prestamo module - Repository binding
    App\Prestamo\Domain\Repository\PrestamoRepositoryInterface:
        class: App\Prestamo\Infrastructure\Persistence\Doctrine\Repository\DoctrinePrestamoRepository

    # Auth module - Event Subscriber
    App\Auth\Infrastructure\EventSubscriber\AuthSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # Make MessageBus public for scripts
    Symfony\Component\Messenger\MessageBusInterface:
        alias: 'messenger.bus.default'
        public: true
